# Copyright 2026 JINX Enterprise Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Cognitive loop orchestration, execution controller, and IDE-IPC layer for JINX."""

import json
import logging
import re
import sys
import textwrap
from typing import Any, Dict, List, Optional, Tuple

import yaml

from .prompts import SYSTEM_PROMPT, TOOL_DEPTH_CRITICAL_MSG, construct_round_prompt
from .state import merge_state, read_jinx, write_jinx
from .tools import tool_schema

# Configure package-level logger
logger = logging.getLogger("jinx.runner")

# Constants defining maximum execution safety boundaries
HARD_CAP: int = 40
TOOL_DEPTH_CAP: int = 20


def parse_state_block(text: str) -> Optional[Dict[str, Any]]:
    """Extracts and parses the serialized JINX state block from standard markdown code fences.

    It searches for standard markdown YAML or JSON code block fences (e.g., ```yaml,
    ```yml, or ```json), extracts the raw text inside, and decodes it.

    Args:
        text (str): The raw text output generated by the LLM.

    Returns:
        Optional[Dict[str, Any]]: The parsed state dictionary if a valid state
            block is found and correctly decoded; otherwise, None.
    """
    # Parse markdown code blocks (e.g. ```yaml ... ``` or ```json ... ```)
    # We allow optional leading spaces/indentation before the code block fences.
    code_block_pattern = r"[ \t]*```(?:json|yaml|yml)?[ \t]*\r?\n(.*?)\r?\n[ \t]*```"
    code_matches = list(re.finditer(code_block_pattern, text, re.DOTALL))
    
    if code_matches:
        for match in reversed(code_matches):
            raw = match.group(1)
            # Remove common leading indentation from all lines so YAML parses correctly
            raw = textwrap.dedent(raw).strip()
            try:
                # yaml.safe_load parses both standard YAML and JSON perfectly
                data = yaml.safe_load(raw)
                if isinstance(data, dict):
                    # A valid JINX state block must contain at least 2 of the expected core state keys
                    # to prevent matching unrelated configuration files or generic code blocks.
                    state_keys = {"task", "facts", "scores", "debt", "open", "exit_ready", "deadlock"}
                    if len(set(data.keys()) & state_keys) >= 2:
                        return data
            except yaml.YAMLError:
                continue

    logger.debug("No valid structured markdown state block found in response.")
    return None


def check_exit(scores: List[Dict[str, Any]], min_rounds: int, rnd: int) -> bool:
    """Evaluates whether the cognitive loop is ready to terminate based on score trends.

    The loop exits if we have completed at least `min_rounds` rounds, have a
    minimum history of three score entries, have achieved all-pass status, and
    the performance has converged (i.e. the best score of the last three rounds
    does not exceed the historical peak before those last three rounds).

    Args:
        scores (List[Dict[str, Any]]): The list of historical round evaluations.
        min_rounds (int): The configured minimum execution round count.
        rnd (int): The current active round index.

    Returns:
        bool: True if exit criteria are fully satisfied; False otherwise.
    """
    if rnd < min_rounds or len(scores) < 3:
        return False

    # Verify if "all_pass" was ever achieved in any historical round
    if not any(s.get("all_pass") for s in scores):
        return False

    # Performance comparison between the recent three rounds and the prior history
    last3_best = max(s.get("pass_count", 0) for s in scores[-3:])
    prior_history = scores[:-3]
    if not prior_history:
        # If there is no prior history to compare against (exactly 3 rounds executed)
        # and top.all_pass is satisfied, we treat it as a clean convergence and exit.
        return True

    prior_best = max((s.get("pass_count", 0) for s in prior_history), default=0)
    return last3_best <= prior_best


def _get_val(obj: Any, key: str, default: Any = None) -> Any:
    """Helper to get a value from either a dictionary or an object attribute."""
    if isinstance(obj, dict):
        return obj.get(key, default)
    if hasattr(obj, key):
        return getattr(obj, key)
    return default


def _are_approaches_similar(entry1: Any, entry2: Any) -> bool:
    """Calculates semantic similarity between two approach graphs or falls back to text-matching.

    Uses combined Jaccard similarity of normalized node IDs (50%) and semantic relationship
    triples (50%). If the similarity is >= 0.7, the approaches are considered similar.
    If graph data is missing or completely empty for either entry, gracefully falls back
    to exact string matching of approach names.
    """
    graph1 = _get_val(entry1, "approach_graph")
    graph2 = _get_val(entry2, "approach_graph")

    def extract_graph_data(g: Any) -> Optional[Dict[str, Any]]:
        if g is None:
            return None
        if hasattr(g, "model_dump"):
            return g.model_dump()
        if isinstance(g, dict):
            return g
        return None

    g1 = extract_graph_data(graph1)
    g2 = extract_graph_data(graph2)

    if not g1 or not g2:
        # Fallback to text matching
        app1 = _get_val(entry1, "approach", "")
        app2 = _get_val(entry2, "approach", "")
        return app1 == app2

    nodes1 = {n.get("id", "").strip().lower() for n in g1.get("nodes", []) if n.get("id")} if isinstance(g1.get("nodes"), list) else set()
    nodes2 = {n.get("id", "").strip().lower() for n in g2.get("nodes", []) if n.get("id")} if isinstance(g2.get("nodes"), list) else set()

    edges1 = {
        (e.get("source", "").strip().lower(), e.get("relation", "").strip().lower(), e.get("target", "").strip().lower())
        for e in g1.get("edges", [])
        if e.get("source") and e.get("target")
    } if isinstance(g1.get("edges"), list) else set()

    edges2 = {
        (e.get("source", "").strip().lower(), e.get("relation", "").strip().lower(), e.get("target", "").strip().lower())
        for e in g2.get("edges", [])
        if e.get("source") and e.get("target")
    } if isinstance(g2.get("edges"), list) else set()

    # If either graph has no entities or edges, fall back to raw text matching
    if not nodes1 and not edges1 and not nodes2 and not edges2:
        app1 = _get_val(entry1, "approach", "")
        app2 = _get_val(entry2, "approach", "")
        return app1 == app2

    # Calculate Node Jaccard
    if nodes1 or nodes2:
        node_sim = len(nodes1.intersection(nodes2)) / len(nodes1.union(nodes2))
    else:
        node_sim = None

    # Calculate Edge Jaccard
    if edges1 or edges2:
        edge_sim = len(edges1.intersection(edges2)) / len(edges1.union(edges2))
    else:
        edge_sim = None

    if node_sim is not None and edge_sim is not None:
        combined_sim = 0.5 * node_sim + 0.5 * edge_sim
    elif node_sim is not None:
        combined_sim = node_sim
    elif edge_sim is not None:
        combined_sim = edge_sim
    else:
        combined_sim = 0.0

    return combined_sim >= 0.7


def _select_representative(cluster: List[Any], entry: Any) -> Any:
    """Selects the first similar representative of the cluster to compare against the new entry.

    Provides single-linkage behavior to handle transitive approach similarity chains cleanly.
    Returns the similar member if found, or None.
    """
    if not cluster:
        return None

    # Single-linkage: if any member is similar, let that member be the representative
    for member in cluster:
        if _are_approaches_similar(entry, member):
            return member
    return None


def check_deadlock(scores: List[Any], min_rounds: int, rnd: int) -> bool:
    """Determines if the cognitive loop is stuck in a deadlock of repeated failures.

    A deadlock is recognized if we have passed `min_rounds` and any single functional
    requirement has failed across three or more unique strategy/approach clusters.

    Args:
        scores (List[Any]): The list of historical round evaluations.
        min_rounds (int): The configured minimum execution round count.
        rnd (int): The current active round index.

    Returns:
        bool: True if a requirement-level deadlock is detected; False otherwise.
    """
    if rnd < min_rounds:
        return False

    failing_entries_by_req: Dict[str, List[Any]] = {}
    for entry in scores:
        requirements = _get_val(entry, "requirements") or {}
        for req, passed in requirements.items():
            if not passed:
                failing_entries_by_req.setdefault(req, []).append(entry)

    for req, entries in failing_entries_by_req.items():
        clusters: List[List[Any]] = []
        for entry in entries:
            matched_cluster = None
            for cluster in clusters:
                rep = _select_representative(cluster, entry)
                if rep is not None:
                    matched_cluster = cluster
                    break
            if matched_cluster is not None:
                matched_cluster.append(entry)
            else:
                clusters.append([entry])

        if len(clusters) >= 3:
            logger.warning(
                "Deadlock detected on requirement '%s': failed across %d unique strategy clusters.",
                req,
                len(clusters)
            )
            return True

    return False



def get_tool_result_from_editor(tool_use_id: str, name: str, params: Dict[str, Any]) -> Tuple[str, bool, bool]:
    """Dispatches tool invocation via JSON-RPC on stdout and awaits the result from stdin.

    Args:
        tool_use_id (str): The unique transaction/call identifier for the tool.
        name (str): The name of the tool to be executed.
        params (Dict[str, Any]): The input parameters for tool execution.

    Returns:
        Tuple[str, bool, bool]: A tuple containing:
            - The raw string representation of the tool output returned by the host.
            - A boolean indicating if the host editor already sliced the content (was_sliced).
            - A boolean indicating if the invocation encountered an error (is_error).
    """
    payload = {
        "jinx_command": name,
        "tool_use_id": tool_use_id,
        "params": params
    }
    # Direct print to stdout is our JSON-RPC IPC channel
    try:
        print(json.dumps(payload), flush=True)
    except OSError as e:
        logger.error("Failed to transmit JSON-RPC tool invocation payload to stdout: %s", e)
        return f"Error: Failed to transmit payload to stdout: {e}", False, True

    try:
        line = sys.stdin.readline()
        if not line:
            logger.error("Host stdin was closed unexpectedly during tool invocation.")
            return "Error: Editor disconnected or closed stdin.", False, True
        response = json.loads(line)
        is_error = "error" in response or "error" in response.get("status", "").lower() if isinstance(response.get("status"), str) else "error" in response
        output = response.get("output") or response.get("content") or response.get("error") or str(response)
        was_sliced = bool(response.get("sliced") or response.get("is_sliced"))
        return str(output), was_sliced, is_error
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Error receiving or decoding tool result from host stdin: %s", e)
        return f"Error receiving input from editor: {e}", False, True


def request_llm_from_editor(
    system: str,
    messages: List[Dict[str, Any]],
    tools: Optional[List[Dict[str, Any]]] = None
) -> List[Dict[str, Any]]:
    """Delegates LLM message generation to the host editor via IPC.

    Args:
        system (str): The system prompt guidance defining agent behavior.
        messages (List[Dict[str, Any]]): The chronological conversation thread.
        tools (Optional[List[Dict[str, Any]]]): Optional tool declarations to pass to the LLM.

    Returns:
        List[Dict[str, Any]]: The parsed list of block objects returned by the LLM,
            or an empty list if generation fails or is disconnected.
    """
    payload = {
        "jinx_command": "llm_generate",
        "params": {
            "system": system,
            "messages": messages,
            "tools": tools if tools is not None else tool_schema()
        }
    }
    try:
        print(json.dumps(payload), flush=True)
    except OSError as e:
        logger.error("Failed to transmit JSON-RPC LLM request payload to stdout: %s", e)
        return []

    try:
        line = sys.stdin.readline()
        if not line:
            logger.error("Host stdin was closed unexpectedly during LLM generation request.")
            return []
        response = json.loads(line)
        return response.get("content") or []
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Error receiving or decoding LLM response from host stdin: %s", e)
        return []


from pathlib import Path

# Paths for stateless File-IPC protocol
AGENT_DIR: Path = Path(__file__).resolve().parent.parent.parent
REQUEST_PATH: Path = AGENT_DIR / "jinx_request.json"
RESPONSE_PATH: Path = AGENT_DIR / "jinx_response.json"
RUN_STATE_PATH: Path = AGENT_DIR / "jinx_run_state.json"


def clean_up_ipc_files() -> None:
    """Removes temporary IPC communication files to reset/clean the session state."""
    REQUEST_PATH.unlink(missing_ok=True)
    RESPONSE_PATH.unlink(missing_ok=True)
    RUN_STATE_PATH.unlink(missing_ok=True)


def write_llm_request(
    history: List[Dict[str, Any]],
    rnd: int,
    tool_depth: int,
    min_rounds: int,
    task: str
) -> None:
    """Writes the current prompt/history state and requests LLM generation."""
    request_payload = {
        "type": "llm_generate",
        "system": SYSTEM_PROMPT,
        "messages": history,
        "tools": tool_schema()
    }
    try:
        with open(REQUEST_PATH, "w", encoding="utf-8") as f:
            json.dump(request_payload, f, indent=2)
    except OSError as e:
        logger.error("Failed to write llm_generate request to %s: %s", REQUEST_PATH, e)
        raise

    run_state = {
        "rnd": rnd,
        "tool_depth": tool_depth,
        "history": history,
        "waiting_for": "llm_generate",
        "min_rounds": min_rounds,
        "task": task
    }
    try:
        with open(RUN_STATE_PATH, "w", encoding="utf-8") as f:
            json.dump(run_state, f, indent=2)
    except OSError as e:
        logger.error("Failed to write run state metadata to %s: %s", RUN_STATE_PATH, e)
        raise

    print(f"[JINX_WAITING] Requesting LLM completion for Round {rnd}...", flush=True)


def run_file_ipc(task: Optional[str], min_override: Optional[int]) -> None:
    """Orchestrates JINX loop using a stateless File-based IPC protocol."""
    is_resuming = RUN_STATE_PATH.exists() and not task

    if not is_resuming:
        # Initialize a brand-new task session
        jinx = read_jinx()
        if not isinstance(jinx.get("state"), dict):
            jinx["state"] = {}

        if not task:
            logger.error("Cannot start new JINX session without a task description.")
            sys.exit(1)

        jinx["state"]["task"] = task
        jinx["state"]["facts"] = []
        jinx["state"]["scores"] = []
        jinx["state"]["debt"] = []
        jinx["state"]["open"] = []
        jinx["state"]["exit_ready"] = False
        jinx["state"]["deadlock"] = False
        write_jinx(jinx)

        min_rounds = 10
        if min_override is not None:
            min_rounds = min_override
        else:
            protocol_config = jinx.get("protocol")
            if isinstance(protocol_config, dict):
                loop_config = protocol_config.get("loop")
                if isinstance(loop_config, dict):
                    configured_min = loop_config.get("min")
                    if isinstance(configured_min, int):
                        min_rounds = configured_min

        clean_up_ipc_files()

        rnd = 1
        state_dump = yaml.dump(
            jinx["state"],
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False
        )
        user_msg = construct_round_prompt(rnd=rnd, min_rounds=min_rounds, task=task, state_dump=state_dump)
        history = [{"role": "user", "content": user_msg}]

        write_llm_request(history, rnd, 0, min_rounds, task)
        return

    else:
        # Resume a previously serialized execution round
        try:
            with open(RUN_STATE_PATH, "r", encoding="utf-8") as f:
                run_state = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            logger.error("Failed to load JINX run state metadata: %s. Re-initializing...", e)
            clean_up_ipc_files()
            sys.exit(1)

        rnd = run_state["rnd"]
        tool_depth = run_state["tool_depth"]
        history = run_state["history"]
        waiting_for = run_state["waiting_for"]
        min_rounds = run_state["min_rounds"]
        task = run_state["task"]

        if not RESPONSE_PATH.exists():
            logger.error("Awaiting editor response. Please make sure %s is populated.", RESPONSE_PATH)
            sys.exit(1)

        try:
            with open(RESPONSE_PATH, "r", encoding="utf-8") as f:
                response_data = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            logger.error("Failed to read/decode editor response JSON from %s: %s", RESPONSE_PATH, e)
            sys.exit(1)

        # Consume response
        RESPONSE_PATH.unlink(missing_ok=True)

        if waiting_for == "llm_generate":
            raw_content = response_data.get("content") or []
            if isinstance(raw_content, str):
                content_blocks = [{"type": "text", "text": raw_content}]
            elif isinstance(raw_content, list):
                content_blocks = []
                for b in raw_content:
                    if isinstance(b, str):
                        content_blocks.append({"type": "text", "text": b})
                    elif isinstance(b, dict):
                        content_blocks.append(b)
                    else:
                        content_blocks.append({"type": "text", "text": str(b)})
            else:
                content_blocks = [{"type": "text", "text": str(raw_content)}]

            history.append({"role": "assistant", "content": content_blocks})

            full_text = ""
            for block in content_blocks:
                if block.get("type") == "text":
                    full_text += block.get("text", "")

            tool_calls = []
            for block in content_blocks:
                if block.get("type") == "tool_use":
                    tool_calls.append({
                        "id": block.get("id"),
                        "name": block.get("name"),
                        "params": block.get("input") or {}
                    })

            if tool_calls:
                # Post tool executions back to editor
                request_payload = {
                    "type": "tool_calls",
                    "calls": tool_calls
                }
                try:
                    with open(REQUEST_PATH, "w", encoding="utf-8") as f:
                        json.dump(request_payload, f, indent=2)
                except OSError as e:
                    logger.error("Failed to write tool_calls request: %s", e)
                    sys.exit(1)

                run_state["tool_depth"] = tool_depth + 1
                run_state["history"] = history
                run_state["waiting_for"] = "tool_calls"
                try:
                    with open(RUN_STATE_PATH, "w", encoding="utf-8") as f:
                        json.dump(run_state, f, indent=2)
                except OSError as e:
                    logger.error("Failed to write run state updates: %s", e)
                    sys.exit(1)

                print(f"[JINX_WAITING] Requesting tool execution for Round {rnd}...", flush=True)
                return
            else:
                # No tool calls made this round, parse/incorporate the updated Jinx state block
                update = parse_state_block(full_text)
                jinx = read_jinx()
                if update:
                    jinx = merge_state(jinx, update)
                    write_jinx(jinx)

                    scores = jinx["state"].get("scores", [])

                    if update.get("exit_ready") and check_exit(scores, min_rounds, rnd):
                        clean_up_ipc_files()
                        print("[JINX_COMPLETE] Task resolved successfully!", flush=True)
                        return

                    if update.get("deadlock") or check_deadlock(scores, min_rounds, rnd):
                        if not update.get("deadlock"):
                            jinx["state"]["deadlock"] = True
                            write_jinx(jinx)
                        clean_up_ipc_files()
                        print("[JINX_DEADLOCK] Loop aborted due to strategy deadlock.", flush=True)
                        return

                # Transition to next round
                rnd += 1
                if rnd >= HARD_CAP:
                    clean_up_ipc_files()
                    logger.error("Cognitive loop exhausted HARD_CAP.")
                    sys.exit(2)

                jinx = read_jinx()
                state_data = jinx.get("state") or {}
                state_dump = yaml.dump(
                    state_data,
                    allow_unicode=True,
                    default_flow_style=False,
                    sort_keys=False
                )
                user_msg = construct_round_prompt(
                    rnd=rnd,
                    min_rounds=min_rounds,
                    task=task,
                    state_dump=state_dump,
                    missing_state=not update
                )
                history.append({"role": "user", "content": user_msg})

                write_llm_request(history, rnd, 0, min_rounds, task)
                return

        elif waiting_for == "tool_calls":
            results = response_data.get("results") or []
            tool_results = []
            for res in results:
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": res.get("tool_use_id"),
                    "content": res.get("content") or ""
                })

            if tool_depth >= TOOL_DEPTH_CAP:
                logger.warning("Inner tool depth limit reached. Forcing state recovery.")
                tool_results.append({
                    "type": "text",
                    "text": TOOL_DEPTH_CRITICAL_MSG
                })
                history.append({"role": "user", "content": tool_results})

                request_payload = {
                    "type": "llm_generate",
                    "system": SYSTEM_PROMPT,
                    "messages": history,
                    "tools": []
                }
                try:
                    with open(REQUEST_PATH, "w", encoding="utf-8") as f:
                        json.dump(request_payload, f, indent=2)
                except OSError as e:
                    logger.error("Failed to write final summary request: %s", e)
                    sys.exit(1)

                run_state["waiting_for"] = "llm_generate"
                run_state["history"] = history
                try:
                    with open(RUN_STATE_PATH, "w", encoding="utf-8") as f:
                        json.dump(run_state, f, indent=2)
                except OSError as e:
                    logger.error("Failed to write run state updates: %s", e)
                    sys.exit(1)

                print(f"[JINX_WAITING] Requesting final summary completion for Round {rnd}...", flush=True)
                return
            else:
                history.append({"role": "user", "content": tool_results})
                write_llm_request(history, rnd, tool_depth, min_rounds, task)
                return

        else:
            logger.error("Unexpected waiting_for state metadata encountered: '%s'. Cleaning up IPC state and exiting.", waiting_for)
            clean_up_ipc_files()
            sys.exit(1)


def run(task: Optional[str], min_override: Optional[int], ipc_mode: str = "file") -> None:
    """Orchestrates the JINX execution loop across rounds either via JSON-RPC stream or File-based IPC.

    Args:
        task (Optional[str]): The objective prompt assigned to the agent.
        min_override (Optional[int]): User override for the minimum cognitive rounds.
        ipc_mode (str): The IPC protocol ('file' for stateless step-by-step or 'rpc' for duplex stream).
    """
    if ipc_mode == "file":
        run_file_ipc(task, min_override)
        return

    # Original interactive duplex stream JSON-RPC mode fallback
    jinx = read_jinx()
    if not isinstance(jinx.get("state"), dict):
        jinx["state"] = {}
    jinx["state"]["task"] = task or ""
    jinx["state"]["facts"] = []
    jinx["state"]["scores"] = []
    jinx["state"]["debt"] = []
    jinx["state"]["open"] = []
    jinx["state"]["exit_ready"] = False
    jinx["state"]["deadlock"] = False
    write_jinx(jinx)

    min_rounds: int = 10
    if min_override is not None:
        min_rounds = min_override
    else:
        protocol_config = jinx.get("protocol")
        if isinstance(protocol_config, dict):
            loop_config = protocol_config.get("loop")
            if isinstance(loop_config, dict):
                configured_min = loop_config.get("min")
                if isinstance(configured_min, int):
                    min_rounds = configured_min

    rnd: int = 0
    last_round_missing_state: bool = False

    logger.info("Starting JINX cognitive loop (JSON-RPC stream). Task: '%s'. Min rounds: %d", task, min_rounds)

    while rnd < HARD_CAP:
        rnd += 1
        history: List[Dict[str, Any]] = []
        jinx = read_jinx()
        state_data = jinx.get("state")
        if not isinstance(state_data, dict):
            state_data = {}
        state_dump = yaml.dump(
            state_data,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False
        )

        user_msg = construct_round_prompt(
            rnd=rnd,
            min_rounds=min_rounds,
            task=task,
            state_dump=state_dump,
            missing_state=last_round_missing_state
        )
        history.append({"role": "user", "content": user_msg})

        full_text: str = ""
        tool_depth: int = 0
        while True:
            content_blocks = request_llm_from_editor(SYSTEM_PROMPT, history)
            history.append({"role": "assistant", "content": content_blocks})

            for block in content_blocks:
                if block.get("type") == "text":
                    full_text += block.get("text", "")

            tool_results: List[Dict[str, Any]] = []
            for block in content_blocks:
                if block.get("type") == "tool_use":
                    tool_use_id = block.get("id")
                    name = block.get("name")
                    params = block.get("input") or {}

                    result_content, was_sliced, is_error = get_tool_result_from_editor(tool_use_id, name, params)

                    if name == "file_read" and not is_error and not was_sliced:
                        try:
                            start_line = params.get("start_line")
                            end_line = params.get("end_line")
                            if start_line is not None or end_line is not None:
                                lines = result_content.splitlines()
                                if lines:
                                    s_line = int(start_line) if start_line is not None else 1
                                    e_line = int(end_line) if end_line is not None else len(lines)
                                    
                                    if s_line < 1:
                                        raise ValueError(f"start_line must be at least 1 (got {start_line})")
                                    if e_line < 1:
                                        raise ValueError(f"end_line must be at least 1 (got {end_line})")
                                    if s_line > e_line:
                                        raise ValueError(f"start_line ({s_line}) cannot be greater than end_line ({e_line})")
                                        
                                    s_line = max(1, s_line)
                                    if s_line > len(lines):
                                        s_line = len(lines)
                                    e_line = max(s_line, e_line)
                                    if e_line > len(lines):
                                        e_line = len(lines)
                                    sliced_lines = lines[s_line - 1:e_line]
                                    result_content = "\n".join(sliced_lines)
                                else:
                                    result_content = ""
                        except (ValueError, TypeError) as e:
                            logger.error("Failed to parse start_line/end_line in file_read: %s", e)
                            result_content = f"Error: Failed to slice file content: {e}"

                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": tool_use_id,
                        "content": result_content
                    })

            if tool_results:
                tool_depth += 1
                if tool_depth >= TOOL_DEPTH_CAP:
                    logger.warning("Inner tool depth limit reached. Forcing final state block recovery.")
                    tool_results.append({
                        "type": "text",
                        "text": TOOL_DEPTH_CRITICAL_MSG
                    })
                    history.append({"role": "user", "content": tool_results})
                    content_blocks = request_llm_from_editor(SYSTEM_PROMPT, history, tools=[])
                    history.append({"role": "assistant", "content": content_blocks})
                    for block in content_blocks:
                        if block.get("type") == "text":
                            full_text += block.get("text", "")
                    break

                history.append({"role": "user", "content": tool_results})
                continue
            else:
                break

        update = parse_state_block(full_text)
        if update:
            last_round_missing_state = False
            jinx = merge_state(jinx, update)
            write_jinx(jinx)

            scores = jinx["state"].get("scores", [])

            if update.get("exit_ready") and check_exit(scores, min_rounds, rnd):
                logger.info("Execution complete. Criteria met in round %d.", rnd)
                break

            if update.get("deadlock") or check_deadlock(scores, min_rounds, rnd):
                logger.warning("Cognitive loop ended due to deadlock in round %d.", rnd)
                if not update.get("deadlock"):
                    jinx["state"]["deadlock"] = True
                    write_jinx(jinx)
                break
        else:
            last_round_missing_state = True
    else:
        logger.error("Cognitive loop exhausted HARD_CAP (%d rounds) without resolution.", HARD_CAP)
        sys.exit(2)

