# Copyright 2026 JINX Enterprise Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Cognitive loop orchestration, execution controller, and IDE-IPC layer for JINX."""

import json
import logging
import re
import sys
from typing import Any, Dict, List, Optional

import yaml

from .state import merge_state, read_jinx, write_jinx
from .tools import tool_schema

# Configure package-level logger
logger = logging.getLogger("jinx.runner")

# Constants defining maximum execution safety boundaries
HARD_CAP: int = 40
TOOL_DEPTH_CAP: int = 20
STATE_TAG: str = "state"

SYSTEM_PROMPT: str = f"""You are JINX, a single-agent cognitive loop. You execute tasks through disciplined iterative refinement.

LOOP PROTOCOL (enforced externally — each call is one real round):

GATE BEFORE TRY: Write exactly what the previous round failed on. No silent retries.
TRY: Choose an approach genuinely different from all prior approaches this task.
TEST: You have access to bash_exec, file_read, and file_write tools. The host editor/runner will execute them.
SCORE: Per-requirement pass/fail. Not holistic.
GATE BEFORE COMMIT: Functional end-to-end verification required.

STATE PERSISTENCE: Between rounds, your state lives in JINX.yaml on disk. You MUST return an updated state block at the end of your response.

REQUIRED — end every response with this block (valid JSON inside tags, no markdown fences):
<{STATE_TAG}>
{{
  "task": "task as understood",
  "facts": ["scope facts", "constraints found"],
  "scores": [
    {{
      "round": 1,
      "approach": "approach name",
      "prior_failure": "what failed before this round",
      "requirements": {{"req_name": true}},
      "pass_count": 1,
      "all_pass": false
    }}
  ],
  "debt": ["shortcuts taken"],
  "open": ["unresolved issues"],
  "exit_ready": false,
  "deadlock": false
}}
</{STATE_TAG}>
"""


def parse_state_block(text: str) -> Optional[Dict[str, Any]]:
    """Extracts and parses the serialized JINX state block from a response text.

    Args:
        text (str): The raw text output generated by the LLM.

    Returns:
        Optional[Dict[str, Any]]: The parsed state dictionary if a valid state
            block is found and correctly decoded; otherwise, None.
    """
    pattern = rf"<{STATE_TAG}>(.*?)</{STATE_TAG}>"
    matches = list(re.finditer(pattern, text, re.DOTALL))
    if not matches:
        logger.debug("No structured state block matching tags found in response.")
        return None

    match = matches[-1]
    raw = match.group(1).strip()
    # Strip optional markdown code fences if wrapped by the LLM
    raw = re.sub(r"^```[a-z]*\n?", "", raw)
    raw = re.sub(r"\n?```$", "", raw)

    try:
        data = json.loads(raw)
        if isinstance(data, dict):
            return data
        logger.error("State block parsed successfully but was not a dictionary structure.")
        return None
    except json.JSONDecodeError as e:
        logger.error("Failed to decode JSON from extracted state block: %s", e)
        return None


def check_exit(scores: List[Dict[str, Any]], min_rounds: int, rnd: int) -> bool:
    """Evaluates whether the cognitive loop is ready to terminate based on score trends.

    The loop exits if we have completed at least `min_rounds` rounds, have a
    minimum history of three score entries, have achieved all-pass status, and
    the performance has converged (i.e. the best score of the last three rounds
    does not exceed the historical peak before those last three rounds).

    Args:
        scores (List[Dict[str, Any]]): The list of historical round evaluations.
        min_rounds (int): The configured minimum execution round count.
        rnd (int): The current active round index.

    Returns:
        bool: True if exit criteria are fully satisfied; False otherwise.
    """
    if rnd < min_rounds or len(scores) < 3:
        return False

    # Verify if "all_pass" was ever achieved in any historical round
    if not any(s.get("all_pass") for s in scores):
        return False

    # Performance comparison between the recent three rounds and the prior history
    last3_best = max(s.get("pass_count", 0) for s in scores[-3:])
    prior_history = scores[:-3]
    if not prior_history:
        # If there is no prior history to compare against (exactly 3 rounds executed)
        # and top.all_pass is satisfied, we treat it as a clean convergence and exit.
        return True

    prior_best = max((s.get("pass_count", 0) for s in prior_history), default=0)
    return last3_best <= prior_best


def check_deadlock(scores: List[Dict[str, Any]], min_rounds: int, rnd: int) -> bool:
    """Determines if the cognitive loop is stuck in a deadlock of repeated failures.

    A deadlock is recognized if we have passed `min_rounds` and any single functional
    requirement has failed across three or more unique strategies/approaches.

    Args:
        scores (List[Dict[str, Any]]): The list of historical round evaluations.
        min_rounds (int): The configured minimum execution round count.
        rnd (int): The current active round index.

    Returns:
        bool: True if a requirement-level deadlock is detected; False otherwise.
    """
    if rnd < min_rounds:
        return False

    failing_approaches: Dict[str, set[str]] = {}
    for entry in scores:
        approach = entry.get("approach", "unknown")
        requirements = entry.get("requirements") or {}
        for req, passed in requirements.items():
            if not passed:
                failing_approaches.setdefault(req, set()).add(approach)

    for req, approaches in failing_approaches.items():
        if len(approaches) >= 3:
            logger.warning(
                "Deadlock detected on requirement '%s': failed across %d unique approaches: %s",
                req,
                len(approaches),
                approaches
            )
            return True

    return False


def get_tool_result_from_editor(tool_use_id: str, name: str, params: Dict[str, Any]) -> str:
    """Dispatches tool invocation via JSON-RPC on stdout and awaits the result from stdin.

    Args:
        tool_use_id (str): The unique transaction/call identifier for the tool.
        name (str): The name of the tool to be executed.
        params (Dict[str, Any]): The input parameters for tool execution.

    Returns:
        str: The raw string representation of the tool output returned by the host.
    """
    payload = {
        "jinx_command": name,
        "tool_use_id": tool_use_id,
        "params": params
    }
    # Direct print to stdout is our JSON-RPC IPC channel
    try:
        print(json.dumps(payload), flush=True)
    except OSError as e:
        logger.error("Failed to transmit JSON-RPC tool invocation payload to stdout: %s", e)
        return f"Error: Failed to transmit payload to stdout: {e}"

    try:
        line = sys.stdin.readline()
        if not line:
            logger.error("Host stdin was closed unexpectedly during tool invocation.")
            return "Error: Editor disconnected or closed stdin."
        response = json.loads(line)
        output = response.get("output") or response.get("content") or str(response)
        return str(output)
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Error receiving or decoding tool result from host stdin: %s", e)
        return f"Error receiving input from editor: {e}"


def request_llm_from_editor(
    system: str,
    messages: List[Dict[str, Any]],
    tools: Optional[List[Dict[str, Any]]] = None
) -> List[Dict[str, Any]]:
    """Delegates LLM message generation to the host editor via IPC.

    Args:
        system (str): The system prompt guidance defining agent behavior.
        messages (List[Dict[str, Any]]): The chronological conversation thread.
        tools (Optional[List[Dict[str, Any]]]): Optional tool declarations to pass to the LLM.

    Returns:
        List[Dict[str, Any]]: The parsed list of block objects returned by the LLM,
            or an empty list if generation fails or is disconnected.
    """
    payload = {
        "jinx_command": "llm_generate",
        "params": {
            "system": system,
            "messages": messages,
            "tools": tools if tools is not None else tool_schema()
        }
    }
    try:
        print(json.dumps(payload), flush=True)
    except OSError as e:
        logger.error("Failed to transmit JSON-RPC LLM request payload to stdout: %s", e)
        return []

    try:
        line = sys.stdin.readline()
        if not line:
            logger.error("Host stdin was closed unexpectedly during LLM generation request.")
            return []
        response = json.loads(line)
        return response.get("content") or []
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Error receiving or decoding LLM response from host stdin: %s", e)
        return []


def run(task: str, min_override: Optional[int]) -> None:
    """Orchestrates the cognitive execution loop for the given task.

    This function reads the local JINX manifest, initializes the active state,
    and runs successive rounds of task analysis, execution, and metric evaluation
    up to a hard cap of rounds.

    Args:
        task (str): The objective or prompt that JINX is assigned to resolve.
        min_override (Optional[int]): User-specified override for minimum rounds.
    """
    jinx = read_jinx()
    if not isinstance(jinx.get("state"), dict):
        jinx["state"] = {}
    jinx["state"]["task"] = task
    jinx["state"]["facts"] = []
    jinx["state"]["scores"] = []
    jinx["state"]["debt"] = []
    jinx["state"]["open"] = []
    jinx["state"]["exit_ready"] = False
    jinx["state"]["deadlock"] = False
    write_jinx(jinx)

    # Resolve minimum rounds from override, JINX.yaml configuration, or fall back to 10
    min_rounds: int = 10
    if min_override is not None:
        min_rounds = min_override
    else:
        protocol_config = jinx.get("protocol")
        if isinstance(protocol_config, dict):
            loop_config = protocol_config.get("loop")
            if isinstance(loop_config, dict):
                configured_min = loop_config.get("min")
                if isinstance(configured_min, int):
                    min_rounds = configured_min

    rnd: int = 0

    logger.info("Starting JINX cognitive loop. Task: '%s'. Min rounds: %d", task, min_rounds)

    while rnd < HARD_CAP:
        rnd += 1
        history: List[Dict[str, Any]] = []
        jinx = read_jinx()
        state_data = jinx.get("state")
        if not isinstance(state_data, dict):
            state_data = {}
        state_dump = yaml.dump(
            state_data,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False
        )

        user_msg = f"ROUND {rnd} of {min_rounds}+\nTASK: {task}\nCURRENT STATE:\n{state_dump}"
        history.append({"role": "user", "content": user_msg})

        full_text: str = ""
        tool_depth: int = 0
        while True:
            # Send conversation history to the LLM via IPC delegation
            content_blocks = request_llm_from_editor(SYSTEM_PROMPT, history)
            history.append({"role": "assistant", "content": content_blocks})

            # Accumulate text content generated by the assistant
            for block in content_blocks:
                if block.get("type") == "text":
                    full_text += block.get("text", "")

            # Process any tool invocation requests emitted by the assistant
            tool_results: List[Dict[str, Any]] = []
            for block in content_blocks:
                if block.get("type") == "tool_use":
                    tool_use_id = block.get("id")
                    name = block.get("name")
                    params = block.get("input") or {}

                    logger.info("Executing tool command '%s' via host editor.", name)
                    result_content = get_tool_result_from_editor(tool_use_id, name, params)

                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": tool_use_id,
                        "content": result_content
                    })

            if tool_results:
                tool_depth += 1
                if tool_depth >= TOOL_DEPTH_CAP:
                    logger.warning("Inner tool-calling depth limit (%d) reached. Invoking final summary round to recover state block.", TOOL_DEPTH_CAP)
                    # Force one last non-tool generation to let the model output its state block safely
                    final_user_msg = (
                        "CRITICAL: The inner tool-calling depth limit has been reached. "
                        "Do not call any more tools. You must immediately output your final thought "
                        "and the exact, complete <state> block to persist your progress and avoid state loss."
                    )
                    tool_results.append({
                        "type": "text",
                        "text": final_user_msg
                    })
                    history.append({"role": "user", "content": tool_results})
                    content_blocks = request_llm_from_editor(SYSTEM_PROMPT, history, tools=[])
                    history.append({"role": "assistant", "content": content_blocks})
                    for block in content_blocks:
                        if block.get("type") == "text":
                            full_text += block.get("text", "")
                    break

                history.append({"role": "user", "content": tool_results})
                # Re-invoke LLM with the results of the tool executions
                continue
            else:
                break

        # Parse updated state returned by the LLM
        update = parse_state_block(full_text)
        if update:
            jinx = merge_state(jinx, update)
            write_jinx(jinx)

            scores = jinx["state"].get("scores", [])

            # Check termination conditions: successful convergence or strategy deadlock
            if update.get("exit_ready") and check_exit(scores, min_rounds, rnd):
                logger.info("Execution complete. Criteria met in round %d.", rnd)
                break

            if update.get("deadlock") or check_deadlock(scores, min_rounds, rnd):
                logger.warning("Cognitive loop ended due to deadlock in round %d.", rnd)
                break
    else:
        logger.error("Cognitive loop exhausted HARD_CAP (%d rounds) without resolution.", HARD_CAP)
        sys.exit(2)

