from __future__ import annotations

import asyncio
from abc import abstractmethod
from dataclasses import dataclass, field
from typing import (
    Any, Awaitable, Callable, Dict, Generic, Iterator, 
    Optional, Protocol, TypeVar, runtime_checkable
)

from jinx.log_paths import BLUE_WHISPERS

T = TypeVar("T")
R = TypeVar("R")


@dataclass(slots=True, frozen=True)
class ContractViolation:
    contract: str
    method: str
    reason: str
    context: Dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class InputPort(Protocol):
    async def __call__(self, queue: asyncio.Queue[str]) -> None: ...
    def cancel(self) -> None: ...


@runtime_checkable
class SpinnerPort(Protocol):
    async def __call__(self, stop_event: asyncio.Event) -> None: ...
    def set_message(self, msg: str) -> None: ...


@runtime_checkable
class ConversationPort(Protocol):
    async def shatter(self, prompt: str, err: str | None = None) -> None: ...
    async def corrupt_report(self, err: str | None) -> None: ...
    async def stream_response(self, prompt: str) -> AsyncIterator[str]: ...


@runtime_checkable
class LoggerPort(Protocol):
    async def glitch_pulse(self) -> str: ...
    async def blast_mem(self, x: str, n: int = 500) -> None: ...
    async def bomb_log(self, t: str, bin: str = BLUE_WHISPERS) -> None: ...
    def set_level(self, level: int) -> None: ...


@runtime_checkable
class BannerPort(Protocol):
    def show_banner(self) -> None: ...
    def get_version(self) -> str: ...


@runtime_checkable
class EventBusPort(Protocol[T]):
    def publish(self, event: T) -> None: ...
    def subscribe(self, handler: Callable[[T], Awaitable[None]]) -> Callable[[], None]: ...
    async def wait_for(self, predicate: Callable[[T], bool], timeout: float | None = None) -> T: ...


@runtime_checkable
class StatePort(Protocol[T]):
    def get(self) -> T: ...
    def set(self, value: T) -> None: ...
    def subscribe(self, callback: Callable[[T, T], None]) -> Callable[[], None]: ...
    def snapshot(self) -> Dict[str, Any]: ...


@runtime_checkable
class QueuePort(Protocol[T]):
    async def put(self, item: T, priority: int = 0) -> bool: ...
    async def get(self) -> T: ...
    def qsize(self) -> int: ...
    def full(self) -> bool: ...
    def empty(self) -> bool: ...


@runtime_checkable
class ExecutorPort(Protocol[T, R]):
    async def execute(self, task: T) -> R: ...
    async def execute_batch(self, tasks: list[T]) -> list[R]: ...
    def cancel_all(self) -> int: ...


@runtime_checkable
class HealthPort(Protocol):
    async def check(self) -> bool: ...
    def get_metrics(self) -> Dict[str, Any]: ...
    def mark_healthy(self) -> None: ...
    def mark_unhealthy(self, reason: str) -> None: ...


@runtime_checkable
class CachePort(Protocol[T]):
    async def get(self, key: str) -> T | None: ...
    async def set(self, key: str, value: T, ttl_s: float | None = None) -> None: ...
    async def delete(self, key: str) -> bool: ...
    async def clear(self) -> int: ...


@runtime_checkable
class PluginPort(Protocol):
    @property
    def name(self) -> str: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def is_running(self) -> bool: ...


class AsyncIterator(Protocol[T]):
    def __aiter__(self) -> "AsyncIterator[T]": ...
    async def __anext__(self) -> T: ...
